// Code generated by MockGen. DO NOT EDIT.
// Source: internal/virt/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/virt/interface.go -destination=internal/virt/mock_virt.go -package=virt
//

// Package virt is a generated GoMock package.
package virt

import (
	reflect "reflect"

	libvirt "github.com/libvirt/libvirt-go"
	gomock "go.uber.org/mock/gomock"
)

// MockVirtManager is a mock of VirtManager interface.
type MockVirtManager struct {
	ctrl     *gomock.Controller
	recorder *MockVirtManagerMockRecorder
	isgomock struct{}
}

// MockVirtManagerMockRecorder is the mock recorder for MockVirtManager.
type MockVirtManagerMockRecorder struct {
	mock *MockVirtManager
}

// NewMockVirtManager creates a new mock instance.
func NewMockVirtManager(ctrl *gomock.Controller) *MockVirtManager {
	mock := &MockVirtManager{ctrl: ctrl}
	mock.recorder = &MockVirtManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVirtManager) EXPECT() *MockVirtManagerMockRecorder {
	return m.recorder
}

// AttachDisk mocks base method.
func (m *MockVirtManager) AttachDisk(vmName string, disk VMDisk) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachDisk", vmName, disk)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachDisk indicates an expected call of AttachDisk.
func (mr *MockVirtManagerMockRecorder) AttachDisk(vmName, disk any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachDisk", reflect.TypeOf((*MockVirtManager)(nil).AttachDisk), vmName, disk)
}

// AttachInterface mocks base method.
func (m *MockVirtManager) AttachInterface(vmName string, iface VMInterface) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachInterface", vmName, iface)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachInterface indicates an expected call of AttachInterface.
func (mr *MockVirtManagerMockRecorder) AttachInterface(vmName, iface any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachInterface", reflect.TypeOf((*MockVirtManager)(nil).AttachInterface), vmName, iface)
}

// ChangeMedia mocks base method.
func (m *MockVirtManager) ChangeMedia(vmName, isoPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeMedia", vmName, isoPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeMedia indicates an expected call of ChangeMedia.
func (mr *MockVirtManagerMockRecorder) ChangeMedia(vmName, isoPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeMedia", reflect.TypeOf((*MockVirtManager)(nil).ChangeMedia), vmName, isoPath)
}

// CloneVM mocks base method.
func (m *MockVirtManager) CloneVM(name, newName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloneVM", name, newName)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloneVM indicates an expected call of CloneVM.
func (mr *MockVirtManagerMockRecorder) CloneVM(name, newName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloneVM", reflect.TypeOf((*MockVirtManager)(nil).CloneVM), name, newName)
}

// Close mocks base method.
func (m *MockVirtManager) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockVirtManagerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockVirtManager)(nil).Close))
}

// CreateNetwork mocks base method.
func (m *MockVirtManager) CreateNetwork(name, bridge, ipRange string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNetwork", name, bridge, ipRange)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNetwork indicates an expected call of CreateNetwork.
func (mr *MockVirtManagerMockRecorder) CreateNetwork(name, bridge, ipRange any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNetwork", reflect.TypeOf((*MockVirtManager)(nil).CreateNetwork), name, bridge, ipRange)
}

// CreateSnapshot mocks base method.
func (m *MockVirtManager) CreateSnapshot(vmName, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSnapshot", vmName, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSnapshot indicates an expected call of CreateSnapshot.
func (mr *MockVirtManagerMockRecorder) CreateSnapshot(vmName, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSnapshot", reflect.TypeOf((*MockVirtManager)(nil).CreateSnapshot), vmName, name)
}

// CreateStoragePool mocks base method.
func (m *MockVirtManager) CreateStoragePool(name, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStoragePool", name, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStoragePool indicates an expected call of CreateStoragePool.
func (mr *MockVirtManagerMockRecorder) CreateStoragePool(name, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStoragePool", reflect.TypeOf((*MockVirtManager)(nil).CreateStoragePool), name, path)
}

// CreateStorageVolume mocks base method.
func (m *MockVirtManager) CreateStorageVolume(poolName, name string, capacity uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStorageVolume", poolName, name, capacity)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStorageVolume indicates an expected call of CreateStorageVolume.
func (mr *MockVirtManagerMockRecorder) CreateStorageVolume(poolName, name, capacity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStorageVolume", reflect.TypeOf((*MockVirtManager)(nil).CreateStorageVolume), poolName, name, capacity)
}

// CreateVM mocks base method.
func (m *MockVirtManager) CreateVM(name string, memory uint64, vcpus uint, isoPath, diskPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVM", name, memory, vcpus, isoPath, diskPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateVM indicates an expected call of CreateVM.
func (mr *MockVirtManagerMockRecorder) CreateVM(name, memory, vcpus, isoPath, diskPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVM", reflect.TypeOf((*MockVirtManager)(nil).CreateVM), name, memory, vcpus, isoPath, diskPath)
}

// DeleteNetwork mocks base method.
func (m *MockVirtManager) DeleteNetwork(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNetwork", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNetwork indicates an expected call of DeleteNetwork.
func (mr *MockVirtManagerMockRecorder) DeleteNetwork(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNetwork", reflect.TypeOf((*MockVirtManager)(nil).DeleteNetwork), name)
}

// DeleteSnapshot mocks base method.
func (m *MockVirtManager) DeleteSnapshot(vmName, snapName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSnapshot", vmName, snapName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSnapshot indicates an expected call of DeleteSnapshot.
func (mr *MockVirtManagerMockRecorder) DeleteSnapshot(vmName, snapName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSnapshot", reflect.TypeOf((*MockVirtManager)(nil).DeleteSnapshot), vmName, snapName)
}

// DeleteStoragePool mocks base method.
func (m *MockVirtManager) DeleteStoragePool(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStoragePool", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStoragePool indicates an expected call of DeleteStoragePool.
func (mr *MockVirtManagerMockRecorder) DeleteStoragePool(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStoragePool", reflect.TypeOf((*MockVirtManager)(nil).DeleteStoragePool), name)
}

// DeleteStorageVolume mocks base method.
func (m *MockVirtManager) DeleteStorageVolume(poolName, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStorageVolume", poolName, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStorageVolume indicates an expected call of DeleteStorageVolume.
func (mr *MockVirtManagerMockRecorder) DeleteStorageVolume(poolName, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStorageVolume", reflect.TypeOf((*MockVirtManager)(nil).DeleteStorageVolume), poolName, name)
}

// DeleteVM mocks base method.
func (m *MockVirtManager) DeleteVM(name string, removeStorage bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVM", name, removeStorage)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVM indicates an expected call of DeleteVM.
func (mr *MockVirtManagerMockRecorder) DeleteVM(name, removeStorage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVM", reflect.TypeOf((*MockVirtManager)(nil).DeleteVM), name, removeStorage)
}

// DestroyVM mocks base method.
func (m *MockVirtManager) DestroyVM(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroyVM", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroyVM indicates an expected call of DestroyVM.
func (mr *MockVirtManagerMockRecorder) DestroyVM(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyVM", reflect.TypeOf((*MockVirtManager)(nil).DestroyVM), name)
}

// DetachDisk mocks base method.
func (m *MockVirtManager) DetachDisk(vmName, target string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetachDisk", vmName, target)
	ret0, _ := ret[0].(error)
	return ret0
}

// DetachDisk indicates an expected call of DetachDisk.
func (mr *MockVirtManagerMockRecorder) DetachDisk(vmName, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetachDisk", reflect.TypeOf((*MockVirtManager)(nil).DetachDisk), vmName, target)
}

// DetachInterface mocks base method.
func (m *MockVirtManager) DetachInterface(vmName, mac string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetachInterface", vmName, mac)
	ret0, _ := ret[0].(error)
	return ret0
}

// DetachInterface indicates an expected call of DetachInterface.
func (mr *MockVirtManagerMockRecorder) DetachInterface(vmName, mac any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetachInterface", reflect.TypeOf((*MockVirtManager)(nil).DetachInterface), vmName, mac)
}

// GetHostStats mocks base method.
func (m *MockVirtManager) GetHostStats() (HostStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostStats")
	ret0, _ := ret[0].(HostStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHostStats indicates an expected call of GetHostStats.
func (mr *MockVirtManagerMockRecorder) GetHostStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostStats", reflect.TypeOf((*MockVirtManager)(nil).GetHostStats))
}

// GetVMAutostart mocks base method.
func (m *MockVirtManager) GetVMAutostart(name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVMAutostart", name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVMAutostart indicates an expected call of GetVMAutostart.
func (mr *MockVirtManagerMockRecorder) GetVMAutostart(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVMAutostart", reflect.TypeOf((*MockVirtManager)(nil).GetVMAutostart), name)
}

// GetVMConfig mocks base method.
func (m *MockVirtManager) GetVMConfig(name string) (VMConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVMConfig", name)
	ret0, _ := ret[0].(VMConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVMConfig indicates an expected call of GetVMConfig.
func (mr *MockVirtManagerMockRecorder) GetVMConfig(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVMConfig", reflect.TypeOf((*MockVirtManager)(nil).GetVMConfig), name)
}

// GetVMStats mocks base method.
func (m *MockVirtManager) GetVMStats(name string, prevStats VMStats) (VMStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVMStats", name, prevStats)
	ret0, _ := ret[0].(VMStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVMStats indicates an expected call of GetVMStats.
func (mr *MockVirtManagerMockRecorder) GetVMStats(name, prevStats any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVMStats", reflect.TypeOf((*MockVirtManager)(nil).GetVMStats), name, prevStats)
}

// ListNetworks mocks base method.
func (m *MockVirtManager) ListNetworks() ([]Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNetworks")
	ret0, _ := ret[0].([]Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNetworks indicates an expected call of ListNetworks.
func (mr *MockVirtManagerMockRecorder) ListNetworks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNetworks", reflect.TypeOf((*MockVirtManager)(nil).ListNetworks))
}

// ListSnapshots mocks base method.
func (m *MockVirtManager) ListSnapshots(vmName string) ([]VMSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSnapshots", vmName)
	ret0, _ := ret[0].([]VMSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSnapshots indicates an expected call of ListSnapshots.
func (mr *MockVirtManagerMockRecorder) ListSnapshots(vmName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSnapshots", reflect.TypeOf((*MockVirtManager)(nil).ListSnapshots), vmName)
}

// ListStoragePools mocks base method.
func (m *MockVirtManager) ListStoragePools() ([]StoragePool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStoragePools")
	ret0, _ := ret[0].([]StoragePool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStoragePools indicates an expected call of ListStoragePools.
func (mr *MockVirtManagerMockRecorder) ListStoragePools() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStoragePools", reflect.TypeOf((*MockVirtManager)(nil).ListStoragePools))
}

// ListStorageVolumes mocks base method.
func (m *MockVirtManager) ListStorageVolumes(poolName string) ([]StorageVolume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStorageVolumes", poolName)
	ret0, _ := ret[0].([]StorageVolume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStorageVolumes indicates an expected call of ListStorageVolumes.
func (mr *MockVirtManagerMockRecorder) ListStorageVolumes(poolName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStorageVolumes", reflect.TypeOf((*MockVirtManager)(nil).ListStorageVolumes), poolName)
}

// ListVMs mocks base method.
func (m *MockVirtManager) ListVMs() ([]VM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVMs")
	ret0, _ := ret[0].([]VM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVMs indicates an expected call of ListVMs.
func (mr *MockVirtManagerMockRecorder) ListVMs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVMs", reflect.TypeOf((*MockVirtManager)(nil).ListVMs))
}

// OpenConsole mocks base method.
func (m *MockVirtManager) OpenConsole(name string) (*libvirt.Stream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenConsole", name)
	ret0, _ := ret[0].(*libvirt.Stream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenConsole indicates an expected call of OpenConsole.
func (mr *MockVirtManagerMockRecorder) OpenConsole(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenConsole", reflect.TypeOf((*MockVirtManager)(nil).OpenConsole), name)
}

// RebootVM mocks base method.
func (m *MockVirtManager) RebootVM(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RebootVM", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// RebootVM indicates an expected call of RebootVM.
func (mr *MockVirtManagerMockRecorder) RebootVM(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebootVM", reflect.TypeOf((*MockVirtManager)(nil).RebootVM), name)
}

// ResetVM mocks base method.
func (m *MockVirtManager) ResetVM(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetVM", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetVM indicates an expected call of ResetVM.
func (mr *MockVirtManagerMockRecorder) ResetVM(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetVM", reflect.TypeOf((*MockVirtManager)(nil).ResetVM), name)
}

// ResumeVM mocks base method.
func (m *MockVirtManager) ResumeVM(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeVM", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResumeVM indicates an expected call of ResumeVM.
func (mr *MockVirtManagerMockRecorder) ResumeVM(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeVM", reflect.TypeOf((*MockVirtManager)(nil).ResumeVM), name)
}

// RevertToSnapshot mocks base method.
func (m *MockVirtManager) RevertToSnapshot(vmName, snapName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevertToSnapshot", vmName, snapName)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevertToSnapshot indicates an expected call of RevertToSnapshot.
func (mr *MockVirtManagerMockRecorder) RevertToSnapshot(vmName, snapName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevertToSnapshot", reflect.TypeOf((*MockVirtManager)(nil).RevertToSnapshot), vmName, snapName)
}

// SetMemory mocks base method.
func (m *MockVirtManager) SetMemory(name string, memory uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMemory", name, memory)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMemory indicates an expected call of SetMemory.
func (mr *MockVirtManagerMockRecorder) SetMemory(name, memory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMemory", reflect.TypeOf((*MockVirtManager)(nil).SetMemory), name, memory)
}

// SetNetworkAutostart mocks base method.
func (m *MockVirtManager) SetNetworkAutostart(name string, autostart bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNetworkAutostart", name, autostart)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetNetworkAutostart indicates an expected call of SetNetworkAutostart.
func (mr *MockVirtManagerMockRecorder) SetNetworkAutostart(name, autostart any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNetworkAutostart", reflect.TypeOf((*MockVirtManager)(nil).SetNetworkAutostart), name, autostart)
}

// SetStoragePoolAutostart mocks base method.
func (m *MockVirtManager) SetStoragePoolAutostart(name string, autostart bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStoragePoolAutostart", name, autostart)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStoragePoolAutostart indicates an expected call of SetStoragePoolAutostart.
func (mr *MockVirtManagerMockRecorder) SetStoragePoolAutostart(name, autostart any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStoragePoolAutostart", reflect.TypeOf((*MockVirtManager)(nil).SetStoragePoolAutostart), name, autostart)
}

// SetVCPUs mocks base method.
func (m *MockVirtManager) SetVCPUs(name string, vcpus uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetVCPUs", name, vcpus)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetVCPUs indicates an expected call of SetVCPUs.
func (mr *MockVirtManagerMockRecorder) SetVCPUs(name, vcpus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVCPUs", reflect.TypeOf((*MockVirtManager)(nil).SetVCPUs), name, vcpus)
}

// SetVMAutostart mocks base method.
func (m *MockVirtManager) SetVMAutostart(name string, autostart bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetVMAutostart", name, autostart)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetVMAutostart indicates an expected call of SetVMAutostart.
func (mr *MockVirtManagerMockRecorder) SetVMAutostart(name, autostart any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVMAutostart", reflect.TypeOf((*MockVirtManager)(nil).SetVMAutostart), name, autostart)
}

// ShutdownVM mocks base method.
func (m *MockVirtManager) ShutdownVM(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShutdownVM", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// ShutdownVM indicates an expected call of ShutdownVM.
func (mr *MockVirtManagerMockRecorder) ShutdownVM(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShutdownVM", reflect.TypeOf((*MockVirtManager)(nil).ShutdownVM), name)
}

// StartNetwork mocks base method.
func (m *MockVirtManager) StartNetwork(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartNetwork", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartNetwork indicates an expected call of StartNetwork.
func (mr *MockVirtManagerMockRecorder) StartNetwork(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartNetwork", reflect.TypeOf((*MockVirtManager)(nil).StartNetwork), name)
}

// StartStoragePool mocks base method.
func (m *MockVirtManager) StartStoragePool(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartStoragePool", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartStoragePool indicates an expected call of StartStoragePool.
func (mr *MockVirtManagerMockRecorder) StartStoragePool(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartStoragePool", reflect.TypeOf((*MockVirtManager)(nil).StartStoragePool), name)
}

// StartVM mocks base method.
func (m *MockVirtManager) StartVM(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartVM", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartVM indicates an expected call of StartVM.
func (mr *MockVirtManagerMockRecorder) StartVM(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartVM", reflect.TypeOf((*MockVirtManager)(nil).StartVM), name)
}

// StopNetwork mocks base method.
func (m *MockVirtManager) StopNetwork(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopNetwork", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopNetwork indicates an expected call of StopNetwork.
func (mr *MockVirtManagerMockRecorder) StopNetwork(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopNetwork", reflect.TypeOf((*MockVirtManager)(nil).StopNetwork), name)
}

// StopStoragePool mocks base method.
func (m *MockVirtManager) StopStoragePool(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopStoragePool", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopStoragePool indicates an expected call of StopStoragePool.
func (mr *MockVirtManagerMockRecorder) StopStoragePool(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopStoragePool", reflect.TypeOf((*MockVirtManager)(nil).StopStoragePool), name)
}

// SuspendVM mocks base method.
func (m *MockVirtManager) SuspendVM(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SuspendVM", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// SuspendVM indicates an expected call of SuspendVM.
func (mr *MockVirtManagerMockRecorder) SuspendVM(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuspendVM", reflect.TypeOf((*MockVirtManager)(nil).SuspendVM), name)
}
